module.exports = {
  GROUP_TYPE_LIST_HORIZONTAL: "GROUP_TYPE_LIST_HORIZONTAL",
  GROUP_TYPE_LIST_VERTICAL: "GROUP_TYPE_LIST_VERTICAL", 
  GROUP_TYPE_GRID_HORIZONTAL: "GROUP_TYPE_GRID_HORIZONTAL",
  GROUP_TYPE_GRID_VERTICAL: "GROUP_TYPE_GRID_VERTICAL", 
}