"use strict";

module.exports = {
  PERMISSION_SCOPE_ENTRIES : "entries",
  PERMISSION_SCOPE_GROUPS : "groups",
  PERMISSION_SCOPE_PARTS : "parts",
  PERMISSION_SCOPE_PERMISSIONS : "permissions",
  PERMISSION_SCOPE_PROFILES : "profiles",
  PERMISSION_SCOPE_USERS : "users",
  
  PERMISSION_ACTION_CREATE : "create",
  PERMISSION_ACTION_READ : "read",
  PERMISSION_ACTION_UPDATE : "update",
  PERMISSION_ACTION_DELETE : "delete",
  
  PERMISSION_POSSESSION_ALL: "all",
  PERMISSION_POSSESSION_OWN: "own",
  PERMISSION_POSSESSION_NONE: "none",
  
  PERMISSION_ROLE_ADMIN: "ROLE_ADMIN",
  PERMISSION_ROLE_MEMBER: "ROLE_MEMBER",
}