module.exports = {
  PROFILE_TYPE_1: "PROFILE_TYPE_MAIN",
  PROFILE_TYPE_2: "PROFILE_TYPE_HEADER_MAIN", 
  PROFILE_TYPE_3: "PROFILE_TYPE_MAIN_SIDE", 
  PROFILE_TYPE_4: "PROFILE_TYPE_HEADER_MAIN_SIDE",
}