"use strict";

module.exports = {
    ROLE: {
        ROLE_ADMIN: "ROLE_ADMIN",
        ROLE_MEMBER: "ROLE_MEMBER"
    },
    COLLECTION: {
        COLLECTION_COMPUTING_TAG: "ComputingTag",
        COLLECTION_EDUCATION: "Education",
        COLLECTION_ENTITY: "Entity",
        COLLECTION_EXPERIENCE: "Experience",
        COLLECTION_FRAMEWORK: "Framework",
        COLLECTION_FRAMEWORK_TAG: "FrameworkTag",
        COLLECTION_INTEREST: "Interest",
        COLLECTION_LANGUAGE: "Language",
        COLLECTION_LINK: "Link",
        COLLECTION_LINK_TAG: "LinkTag",
        COLLECTION_OPERATING_SYSTEM: "OperatingSystem",
        COLLECTION_PROFILE: "Profile",
        COLLECTION_PROGRAMMING_LANGUAGE: "ProgrammingLanguage",
        COLLECTION_PROJECT: "Project",
        COLLECTION_PROJECT_TAG: "ProjectTag",
        COLLECTION_SOFTWARE_FRAMEWORK: "SoftwareFramework",
        COLLECTION_SOFTWARE: "Software",
        COLLECTION_SOFTWARE_TAG: "SoftwareTag",
        COLLECTION_USER: "User"
    },
    PATH: {
        PATH_INDEX: "/",
        PATH_AUTHENTICATION: "/auth",
        PATH_REGISTER: "/register",
        PATH_LOGIN: "/login",
        PATH_COMPUTING_TAGS: "/computingTags",
        PATH_EDUCATIONS: "/educations",
        PATH_ENTITIES: "/entities",
        PATH_EXPERIENCES: "/experiences",
        PATH_FRAMEWORKS: "/frameworks",
        PATH_FRAMEWORK_TAGS: "/frameworkTags",
        PATH_INTERESTS: "/interests",
        PATH_LANGUAGES: "/languages",
        PATH_LINKS: "/links",
        PATH_LINK_TAGS: "/linkTags",
        PATH_OPERATING_SYSTEMS: "/operatingSystems",
        PATH_PROFILES: "/profiles",
        PATH_PROGRAMMING_LANGUAGES: "/programmingLanguages",
        PATH_PROJECTS: "/projects",
        PATH_PROJECT_TAGS: "/projectTags",
        PATH_SOFTWARE_FRAMEWORKS: "/softwareFrameworks",
        PATH_SOFTWARES: "/softwares",
        PATH_SOFTWARE_TAGS: "/softwareTags",
        PATH_USERS: "/users"
    },
    PARAM: {
        PARAM_ID_COMPUTING_TAG: "ComputingTagId",
        PARAM_ID_EDUCATION: "EducationId",
        PARAM_ID_ENTITY: "EntityId",
        PARAM_ID_EXPERIENCE: "ExperienceId",
        PARAM_ID_FRAMEWORK: "FrameworkId",
        PARAM_ID_FRAMEWORK_TAG: "FrameworkTagId",
        PARAM_ID_INTEREST: "InterestId",
        PARAM_ID_LANGUAGE: "LanguageId",
        PARAM_ID_LINK: "LinkId",
        PARAM_ID_LINK_TAG: "LinkTagId",
        PARAM_ID_OPERATING_SYSTEM: "OperatingSystemId",
        PARAM_ID_PROFILE: "ProfileId",
        PARAM_ID_PROGRAMMING_LANGUAGE: "ProgrammingLanguageId",
        PARAM_ID_PROJECT: "ProjectId",
        PARAM_ID_PROJECT_TAG: "ProjectTagId",
        PARAM_ID_SOFTWARE_FRAMEWORK: "SoftwareFrameworkId",
        PARAM_ID_SOFTWARE: "SoftwareId",
        PARAM_ID_SOFTWARE_TAG: "SoftwareTagId",
        PARAM_ID_USER: "UserId"
    }
};