# start with node 8 base image
FROM node:8

MAINTAINER Axel LE BOT

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install --production

# Bundle app source
COPY . /usr/src/app

EXPOSE 8080
CMD ["npm","run","start:prod"]
